import {
  Activity,
  BarChart3,
  Cpu,
  Gauge,
  Globe2,
  LayoutDashboard,
  MapPin,
  Megaphone,
  Settings,
  ShieldCheck,
  UserCheck,
  Users,
  Crown,
  Workflow,
} from "lucide-react";

import type { NavConfig } from "./nav.schema";

export const navConfig: NavConfig = {
  version: 1,
  items: [
    {
      id: "dashboard",
      i18nKey: "navigation.dashboard",
      path: "/dashboard",
      icon: Gauge,
      order: 5,
      surfaces: ["sidebar", "top", "breadcrumb"],
      visibility: { roles: ["admin", "manager", "staff"] },
    },
    {
      id: "reports",
      i18nKey: "navigation.reports",
      path: "/reports",
      icon: LayoutDashboard,
      order: 10,
      surfaces: ["sidebar", "top", "breadcrumb"],
      visibility: { roles: ["admin", "manager", "staff"] },
      badge: { type: "dot", source: "reports" },
    },
    {
      id: "operations",
      i18nKey: "navigation.section_election_operations",
      order: 20,
      surfaces: ["sidebar"],
      meta: { variant: "section" },
      breadcrumb: { hide: true },
      children: [
        {
          id: "operations.controlCenter",
          i18nKey: "navigation.control_center",
          path: "/control-center",
          icon: Workflow,
          order: 5,
          surfaces: ["sidebar", "breadcrumb"],
          visibility: { roles: ["admin", "manager", "staff"] },
        },
        {
          id: "operations.elections",
          i18nKey: "navigation.elections",
          path: "/elections",
          icon: Gauge,
          order: 10,
          surfaces: ["sidebar", "breadcrumb"],
          children: [
            {
              id: "operations.elections.detail",
              i18nKey: "navigation.election_detail",
              path: "/elections/:id",
              order: 1,
              surfaces: ["breadcrumb"],
              breadcrumb: { i18nKey: "navigation.election_detail" },
            },
          ],
        },
        {
          id: "operations.geoAreas",
          i18nKey: "navigation.geo_areas",
          path: "/geo-areas",
          icon: Globe2,
          order: 20,
          surfaces: ["sidebar", "breadcrumb"],
          children: [
            {
              id: "operations.geoAreas.detail",
              i18nKey: "navigation.geo_area_detail",
              path: "/geo-areas/:id",
              order: 1,
              surfaces: ["breadcrumb"],
              breadcrumb: { i18nKey: "navigation.geo_area_detail" },
            },
          ],
        },
        {
          id: "operations.zones",
          i18nKey: "navigation.zones_mansoura",
          path: "/zones/mansoura",
          icon: MapPin,
          order: 30,
          surfaces: ["sidebar", "breadcrumb"],
          breadcrumb: { i18nKey: "navigation.zones_mansoura" },
        },
        {
          id: "operations.committees",
          i18nKey: "navigation.committees",
          path: "/committees",
          icon: Users,
          order: 40,
          surfaces: ["sidebar", "breadcrumb"],
          children: [
            {
              id: "operations.committees.detail",
              i18nKey: "navigation.committee_detail",
              path: "/committees/:id",
              order: 1,
              surfaces: ["breadcrumb"],
              breadcrumb: { i18nKey: "navigation.committee_detail" },
            },
          ],
        },
        {
          id: "operations.voters",
          i18nKey: "navigation.voters",
          path: "/voters",
          icon: UserCheck,
          order: 50,
          surfaces: ["sidebar", "breadcrumb"],
          children: [
            {
              id: "operations.voters.detail",
              i18nKey: "navigation.voter_detail",
              path: "/voters/:id",
              order: 1,
              surfaces: ["breadcrumb"],
              breadcrumb: { i18nKey: "navigation.voter_detail" },
            },
          ],
        },
        {
          id: "operations.candidates",
          i18nKey: "navigation.candidates",
          path: "/candidates",
          icon: Crown,
          order: 60,
          surfaces: ["sidebar", "breadcrumb"],
          children: [
            {
              id: "operations.candidates.detail",
              i18nKey: "navigation.candidate_detail",
              path: "/candidates/:id",
              order: 1,
              surfaces: ["breadcrumb"],
              breadcrumb: { i18nKey: "navigation.candidate_detail" },
            },
          ],
        },
      ],
    },
    {
      id: "field",
      i18nKey: "navigation.section_field_resources",
      order: 30,
      surfaces: ["sidebar"],
      meta: { variant: "section" },
      breadcrumb: { hide: true },
      children: [
        {
          id: "field.agents",
          i18nKey: "navigation.agents",
          path: "/agents",
          icon: ShieldCheck,
          order: 10,
          surfaces: ["sidebar", "breadcrumb"],
        },
        {
          id: "field.volunteers",
          i18nKey: "navigation.volunteers",
          path: "/volunteers",
          icon: Users,
          order: 20,
          surfaces: ["sidebar", "breadcrumb"],
          badge: { type: "count", source: "volunteers" },
        },
        {
          id: "field.observations",
          i18nKey: "navigation.observations",
          path: "/observations",
          icon: Activity,
          order: 30,
          surfaces: ["sidebar", "breadcrumb"],
          badge: { type: "count", source: "alerts" },
        },
      ],
    },
    {
      id: "campaign",
      i18nKey: "navigation.section_campaign_intelligence",
      order: 40,
      surfaces: ["sidebar"],
      meta: { variant: "section" },
      breadcrumb: { hide: true },
      children: [
        {
          id: "campaign.campaigns",
          i18nKey: "navigation.campaigns",
          path: "/campaigns",
          icon: Megaphone,
          order: 10,
          surfaces: ["sidebar", "breadcrumb"],
        },
        {
          id: "campaign.automation",
          i18nKey: "navigation.automation",
          path: "/automation",
          icon: Cpu,
          order: 20,
          surfaces: ["sidebar", "breadcrumb"],
        },
        {
          id: "campaign.analytics",
          i18nKey: "navigation.analytics",
          path: "/analytics",
          icon: BarChart3,
          order: 30,
          surfaces: ["sidebar", "top", "breadcrumb"],
          visibility: { flagsAny: ["betaReports", "labs"] },
        },
      ],
    },
    {
      id: "admin",
      i18nKey: "navigation.section_admin",
      order: 100,
      surfaces: ["sidebar"],
      meta: { variant: "section" },
      breadcrumb: { hide: true },
      children: [
        {
          id: "admin.settings",
          i18nKey: "navigation.settings",
          path: "/settings",
          icon: Settings,
          order: 10,
          surfaces: ["sidebar", "breadcrumb"],
          visibility: { roles: ["admin"] },
        },
      ],
    },
  ],
};

export default navConfig;
