// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqzeuryitlzxmdkkogma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxemV1cnlpdGx6eG1ka2tvZ21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNDc3NTcsImV4cCI6MjA3NTYyMzc1N30.sv9kmnsh4Dtg9DjKruH2k7Ti_17GL5aCQK8fMgcnk38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});